# Default values for temperature-ms.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: schwarzit-xx-sit-showcase-docker-local.jfrog.io
  name: weather-app
  pullPolicy: Always
  tag: 575186
  port: 80

service:
  type: ClusterIP
  port: 80

imagePullSecrets:
  - name: regcred

nameOverride: ""
fullnameOverride: ""

serviceAccount: { }

podAnnotations: { }

podSecurityContext: { }

securityContext: { }



ingress: { }

resources: { }

autoscaling: { }

nodeSelector: { }

tolerations: [ ]

affinity: { }
