apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: city-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - weather.ediri.io
      secretName: city-backend
  rules:
    - host: weather.ediri.io
      http:
        paths:
          - path: /
            backend:
              serviceName: weather-app-svc
              servicePort: {{ .Values.service.port }}
