apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL3NjaHdhcnppdC14eC1zaXQtc2hvd2Nhc2UtZG9ja2VyLWxvY2FsLmpmcm9nLmlvIjp7InVzZXJuYW1lIjoidC1kby1zLXNob3djYXNlIiwicGFzc3dvcmQiOiJBS0NwOGh5dDc0c1VYVlNuV2VFREpxaEgybThlU2ZmWnNIOFlHRG13N25qdlo2YUhKbTREdTQ3cHlIWTl0TEZaUVJLZ3FvNnZwIiwiYXV0aCI6ImRDMWtieTF6TFhOb2IzZGpZWE5sT2tGTFEzQTRhSGwwTnpSelZWaFdVMjVYWlVWRVNuRm9TREp0T0dWVFptWmFjMGc0V1VkRWJYYzNibXAyV2paaFNFcHRORVIxTkRkd2VVaFpPWFJNUmxwUlVrdG5jVzgyZG5BPSJ9fX0=
kind: Secret
metadata:
  name: regcred
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
